name: api-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: api-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Tạo .env cho docker-compose (service "tests" có env_file: .env)
      - name: Create .env for compose (login-based)
        run: |
          {
            echo "BASE_URL=${{ secrets.BASE_URL }}"
            echo "API_USERNAME=${{ secrets.API_USERNAME }}"
            echo "API_PASSWORD=${{ secrets.API_PASSWORD }}"
            # optional: nếu bạn cần URL schema cho Schemathesis
            echo "API_SCHEMA_URL=${{ secrets.API_SCHEMA_URL }}"
            # optional: endpoint login tuỳ hệ thống. Test đọc LOGIN_PATH nếu muốn
            echo "LOGIN_PATH=${{ vars.LOGIN_PATH || '/auth/login/' }}"
          } > .env

      - name: Build test image
        run: docker compose build tests

      # PR = smoke; main/manual = full
      - name: Decide markers
        id: plan
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "MARKS=-m smoke" >> "$GITHUB_OUTPUT"
          else
            echo "MARKS=" >> "$GITHUB_OUTPUT"
          fi

      - name: Run tests in Docker (login inside tests)
        run: |
          docker compose run --rm tests \
            pytest ${{ steps.plan.outputs.MARKS }} -n auto \
              --alluredir=/app/reports/allure-results

      - name: Fix permissions for artifacts
        if: always()
        run: sudo chown -R $USER:$USER reports || true

      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      # (tuỳ chọn) build Allure HTML bằng container official
      - name: Generate Allure HTML
        if: always()
        run: |
          docker compose --profile allure run --rm allure
          sudo chown -R $USER:$USER reports/allure || true
      - name: Upload Allure HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure
