name: api-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run smoke + regression
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.API_USERNAME }}
          PASSWORD: ${{ secrets.API_PASSWORD }}
          API_SCHEMA_URL: ${{ secrets.API_SCHEMA_URL }}
        run: |
          pytest -m "not contract and not schemathesis and not perf" -n auto --alluredir=reports/allure
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure

  schemathesis:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run schemathesis
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_SCHEMA_URL: ${{ secrets.API_SCHEMA_URL }}
        run: pytest -m schemathesis --alluredir=reports/allure
      - uses: actions/upload-artifact@v4
        with:
          name: allure-results-schemathesis
          path: reports/allure

  contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pact consumer tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: pytest -m contract tests/contract/consumer --alluredir=reports/allure
      - uses: actions/upload-artifact@v4
        with:
          name: pact-files
          path: pact/pacts
